### ISSUE TITLE
send.fs walletconnect login

### ISSUE THREAD

**Issue by anatoly-bogatyrev** [nspcc-dev/send-fs-neo-org#9]
# Description
Для send.fs должен быть логин через walletconnect.
- рест запрос на выписывание токена (подготовка структуры).
- подписать полученную структуру кошельком пользователя через walletconnect - и этот токен должен прикладываться к auth-хидеру при put'е объектов через send.fs.

# TODO
- [x] https://github.com/nspcc-dev/neofs-cdn-ui/issues/1
- [x] https://github.com/nspcc-dev/neofs-aio/issues/24
- [x] Проверить схему аутентификации и загрузки объектов в этом окружении
- [ ] Обновить NeoFS инфраструктуру с поддержкой wallet connect подписей
- [ ] Развернуть в публичной инфраструктуре REST Gateway
- [ ] Добавить логин с помощью walletconnect для send.fs

**Comment by roman-khimov** [comment]
I don't think we can do it the way it was intended for send.fs.neo.org --- with email still validated and attached to headers. We have panel.fs.neo.org now for proper object management and send.fs.neo.org can just stay as is.
